### ISSUE TITLE
Install correct versions of extensions for PHPSpec2

### ISSUE THREAD

**Issue by ek9** [richardmiller/BehatSpec#16]
I was checking backwards compatibility, and I am wondering if this will cause problems (this is an old build that depended on phpspec2), now installs the following versions:

    Installing behat/behat (v3.3.0) Loading from cache
    Installing phpspec/phpspec (2.5.0) Loading from cache
    Installing ciaranmcnulty/phpspec-typehintedmethods (1.1.3) Loading from cache
    Installing rmiller/phpspec-run-extension (0.4.1) Downloading: 100%
    Installing rmiller/exemplify-extension (0.4.1) Downloading: 100%
    Installing rmiller/phpspec-extension (0.4.1) Downloading: 100%
    Installing rmiller/error-extension (0.5.0) Downloading: 100%
    Installing rmiller/behat-spec (0.3.0) Loading from cache

Are 0.4.1 version of extensions are not compatible with phpspec2, we need to somehow direct users installing the right versions.

**Comment by ek9** [comment]
I've prepared #17 for this, however, you first need to make the following steps before we could merge / release:
1. We need a new branch, based out of `0.3.0` commit (lets call it `v0.3`).
2. Once there is the branch, I will update #17 to target the `v0.3` branch. We can issue any fixes for `0.3.1`, to sort out version contstrains (comments regarding that on #17 )
3. Once you merge PR to `v0.3` branch, you can tag it as `0.3.1`, which will make for a release on packagist.
4. If you don't plan to maintain `0.3` series anymore, you can at that point just merge `v0.3` branch to master (manually with `--no-ff`), which will make sure that `0.3.1` is preserved. After that the `v0.3` branch can be removed.

**Comment by pocky** [comment]
I don't see any reason to maintain 0.3 anymore. The problem with Exemplify on Behat 3 was important for users but now it's fixed.

The idea on #17 with `phpspec: <3.0` is good for projects in production with CI who download Behat/phpspec for each builds.

**Comment by ek9** [comment]
Yeah if maintaining isn't needed anymore, then once it's tagged, if you merge it into `master` via `git merge --no-ff BRANCH`, you will be able to remove it as it will be preserved in history via tag.

If someone could make a branch out of `08d7ff6` commit (`v0.3.0`), I will change #17 to PR to that.

I have also added the `phpspec ~2.0` as a requirement in #17 (as I don't think `v1` is supported). Let me know otherwise.

**Comment by ek9** [comment]
ping @richardmiller (could you please make a branch out of `08d7ff6` commit (v0.3.0) and push it, so I can re-target #17 to that for 0.3.1 fix). Thanks!

**Comment by richardmiller** [comment]
@ek9 I've created this from that commit https://github.com/richardmiller/BehatSpec/tree/phpspec2-support

**Comment by ek9** [comment]
Thanks, I've rebased the PR, should be good to merge / release as 0.3.1

**Comment by richardmiller** [comment]
Thank you, merged and tagged. You're correct that phpspec 1 is not supported (2 was a complete rewrite).

**Comment by ek9** [comment]
This has to be reopened as I messed up the version definitions and they still allowed installing incorrect versions.
