### ISSUE TITLE
Minimum stability set to `dev` ?

### ISSUE THREAD

**Issue by ek9** [richardmiller/BehatSpec#21]
I noticed that `minimum-stability` is set to `dev`. This makes development and testing of this package rather awkward as it always installs latest `dev-master` version instead of using the version constraints specified in `composer.json`.

I believe this was set by accident. This setting does not impact those, who are just using this library as a dependency. Now when developing and testing this, we probably want to install versions specified in `composer.json` instead of master.

More info on `minimum-stability`: https://getcomposer.org/doc/04-schema.md#minimum-stability

**Comment by richardmiller** [comment]
I think I set it to that originally when there were not tagged versions on the dependencies and when there was a need to use an untagged feature in phpspec and then just never removed it.
