### ISSUE TITLE
ExempifyExtension: behat tests fail due to missing global `expect()` function

### ISSUE THREAD

**Issue by ek9** [richardmiller/BehatSpec#24]
ExemplifyExtension behat tests fail due to missing global `expect()` function

**Comment by richardmiller** [comment]
It should be provided by this package - https://github.com/BossaConsulting/phpspec2-expect

Not sure what happened but it may have previously been a dependency of phpspec but is not anymore

**Comment by richardmiller** [comment]
That said it doesn't have a version that will work with latest phpspec 3 and the tests are broken for other reasons as well. I have a fix just need to clean up and will PR once done.
