### ISSUE TITLE
Enable Automated testing of extensions

### ISSUE THREAD

**Issue by ek9** [richardmiller/BehatSpec#27]
We need to sort out testing of extensions. There are now phpspec / behat specific tests in specific extensions. We either need to make sure these are activated / run upon making commits to current repository.

We have two options for this:
a) Update main repo's testing to run phpspec / behat tests in extension specific directories
b) Consolidate phpspec / behat tests and run them once in the main repository

Let me know what you think so I can do a PR.

**Comment by ek9** [comment]
This is also semi-related to #24 as we would also need to make sure that those tests pass when this issue is implemented.

**Comment by richardmiller** [comment]
I think they may as well be consolidated into one place in the main repo. Any changes will need to be made in the main repo so not sure there's much value in having them in the read only split repos.

**Comment by ek9** [comment]
I agree it would make most sense to keep them in one place instead. I'll make a quick PR for this just to put them together. Also #24 is semi related to this, so you migh want to merge that first (otherwise merge my PR and rebase #24 against it).

**Comment by ek9** [comment]
I have also made an issue to update main repositories `src/` directory to be PSR-4 compatible so we can setup phpspec tests for all extensions via single `phpspec.yml`.
