### ISSUE TITLE
READMEs contain wrong examples for phpspec.yml

### ISSUE THREAD

**Issue by docteurklein** [richardmiller/BehatSpec#4]
Hi!

Correct me if I'm wrong, but according to http://www.phpspec.net/en/latest/cookbook/configuration.html#extensions , the `extensions` key should be at the root of the file.

I guess this typo is spread out in this README but also in its related projects.

I had hard time finding the problem after having copy-pasted the snippet :)

**Comment by pocky** [comment]
:+1:

fix in 08d7ff6ec5d660c6f62bc8c248707378b2fba4ee
