### ISSUE TITLE
behat extension file or class could not be located

### ISSUE THREAD

**Issue by Lionel-Daelemans** [richardmiller/BehatSpec#6]
Hello!

I'm trying to configure BehatSpec on my project but Behat can't seem to find it...
I've checked the requirements, and added the extension to beat.yml but I keep getting the same error
```
[Behat\Testwork\ServiceContainer\Exception\ExtensionInitializationException]
  `0` extension file or class could not be located.
```

I'm a newbie with behat & phpspec so I'm obviously missing something but I will really appreciate some help! :-)

You can check project repo [Lionel-Daelemans/advent_of_code_2015](https://github.com/Lionel-Daelemans/advent_of_code_2015/tree/better-bdd) to see if you spot the error.

Thanks in advance!

**Comment by richardmiller** [comment]
Hi, it looks like you don't make the extensions an array in the config file when they are nested under the profile. Oddly it appears to work either way when not nested under a profile. I've opened a PR to your repo with the change here - https://github.com/Lionel-Daelemans/advent_of_code_2015/pull/6 and I'll update our readme file as well.

**Comment by Lionel-Daelemans** [comment]
thanks for the quick update! extension is working fine now!
